services:
  nfe-microservice:
    build: .
    container_name: nfe-microservice
    ports:
      - "80:8010"
    environment:
      - PYTHONUNBUFFERED=1
    # Se precisar montar volumes para desenvolvimento, descomente abaixo:
    # volumes:
    #   - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8010
